app:
  api:
    swagger:
      enable: true
      
hibernate:
  cache:
    region:
      factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    use_second_level_cache: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 20KB
      max-file-size: 10MB
      max-request-size: 20MB
